import './globals.css'
import Navbar from "./components/Navbar"




export const metadata = {
  title: 'Aditya Aryan',
  description: 'Generated by create next app',
  visualViewport: 'width=device-width, user-scalable=no'
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className='flex flex-col'>
        <Navbar />
          {children}
        </body>
    </html>
  )
}
